version: '1.0'
stages:
  - clone
  - build
  - test
steps:
  clone:
    title: Cloning repository
    type: git-clone
    repo: https://github.com/codefresh-io/cli/
    revision: master
    stage: clone
  build:
    title: Building Docker image
    type: build
    image_name: codefresh-io/cli
    working_directory: ${{clone}}
    tag: latest
    dockerfile: Dockerfile
    stage: build
  test:
    title: Running test
    type: freestyle
    image: codefresh-io/cli
    working_directory: ${{clone}}
    commands:
      - ls
    stage: test
spec:
  triggers:
    - name: acceptance-india
      type: git
      repo: lrochette/pipeline-creator
      events:
        - push.heads
      pullRequestAllowForkEvents: false
      commentRegex: /.*/gi
      branchRegex: /codefresh/gi
      branchRegexInput: regex
      provider: github
      disabled: true
      options:
        noCache: false
        noCfCache: false
        resetVolume: false
      verified: true
      context: github
      contexts: []
      variables:
        - key: GEO_LOCATION
          value: india
        - key: CLUSTER_NAME
          value: qa-india-cluster
        - key: NAMESPACE
          value: codefresh-beauto
        - key: RELEASE_NAME
          value: acceptance-codefresh
        - key: ENV
          value: beauto
      runtimeEnvironment:
        name: qa.india.atlas-antelope.com/codefresh
        cpu: 1000m
        memory: 1024Mi
        dindStorage: nullGi
    - name: acceptance-mx
      type: git
      repo: lrochette/pipeline-creator
      events:
        - push.heads
      pullRequestAllowForkEvents: false
      commentRegex: /.*/gi
      branchRegex: /codefresh/gi
      branchRegexInput: regex
      provider: github
      disabled: true
      options:
        noCache: false
        noCfCache: false
        resetVolume: false
      verified: true
      context: github
      contexts: []
      variables:
        - key: GEO_LOCATION
          value: mx
        - key: CLUSTER_NAME
          value: dev-mx-cluster
        - key: NAMESPACE
          value: codefresh-beauto
        - key: RELEASE_NAME
          value: acceptance-codefresh
        - key: ENV
          value: dev
      runtimeEnvironment:
        name: dev.mx.atlas-antelope.com/codefresh
        cpu: 1000m
        memory: 1024Mi
        dindStorage: nullGi
    - name: triga
      type: git
      repo: lrochette/pipeline-creator
      events:
        - push.heads
      pullRequestAllowForkEvents: false
      commentRegex: /.*/gi
      branchRegex: /branch-a/gi
      branchRegexInput: regex
      provider: github
      disabled: true
      options:
        noCache: false
        noCfCache: false
        resetVolume: false
      verified: true
      context: github
      contexts: []
    - name: trigb
      type: git
      repo: lrochette/pipeline-creator
      events:
        - push.heads
      pullRequestAllowForkEvents: false
      commentRegex: /.*/gi
      branchRegex: /branch-b/gi
      branchRegexInput: regex
      provider: github
      disabled: true
      options:
        noCache: false
        noCfCache: false
        resetVolume: false
      verified: true
      context: github
      contexts: []
