version: "1.0"

stages:
  - clone

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "lrochette/pipeline-creator"
    revision: "master"
    stage: clone

  create_pipeline:
    title: "Creating pipeline"
    image: lrochette/ptm:pipeline_trigger_merge
    working_directory: ${{clone}}
    stage: clone
    commands:
      - /merge.sh
    environment:
      - TRIGGERS="foobar trig1.yml trig2.yml TRIGGERS"
      - SPEC="spec.yml"
