version: "1.0"

stages:
  - clone

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{ORG}}/${{REPO}}"
    revision: "master"
    stage: clone

  # parse_triggers:
  #   title: "Parsing the tirggers"
  #   image: perl
  #   working_directory: ${{REPO}}
  #   commands:
  #     - perl -v
  #     - perl -e parse_triggers.pl

  create_pipeline:
    title: "Creating pipeline"
    image: codefresh/cli
    working_directory: ${{REPO}}
    commands:
      - echo "SPEC: ${{SPEC}}"
      - echo "TRIGGERS: ${{TRIGGERS}}"
      - for f in "${{TRIGGERS}}" ; do
          echo $f
        done
    stage: clone
