version: "1.0"

stages:
  - clone

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{ORG}}/${{REPO}}"
    revision: "master"
    stage: clone

  create_pipeline:
    title: "Creating pipeline"
    image: codefresh/cli
    working_directory: ${{REPO}}
    stage: clone
    commands:
      - echo "SPEC: ${{SPEC}}"
      - echo "TRIGGERS: ${{TRIGGERS}}"
      - |-
        for f in "${{TRIGGERS}}" ; do
          echo $f
        done
