version: "1.0"

stages:
  - clone

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "lrochette/pipeline-creator"
    revision: "master"
    stage: clone

  set-var:
    image: "codefresh/cli"
    stage: clone
    commands:
        - cf_export FOOBAR=weird

  create_pipeline:
    type: pipeline-trigger-merge
    title: "Creating pipeline"
    working_directory: ${{clone}}
    stage: clone
    commands:
      - env
    arguments:
      TRIGGERS: foobar trig1.yml trig2.yml TRIGGERS
      SPEC: spec.yml

  read-var:
    image: "codefresh/cli"
    stage: clone
    commands:
        - env
