version: "1.0"

stages:
  - clone

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{ORG}}/${{REPO}}"
    revision: "master"
    stage: clone

  create_pipeline:
    title: "Creating pipeline"
    image: codefresh/cli
    working_directory: ${{REPO}}
    stage: clone
    commands:
      - |-
        echo "SPEC ${{SPEC}}"
        echo "TRIGGERS ${{TRIGGERS}}"
        process_dir() {
          echo  "process directory $1"
          for FILE in $1/* ; do
            process_file $FILE
          done
        }
        process_file() {
          if [ -f $1 ]; then
            echo  "process file $1"
            cat $1
            if [ $count -eq 1 ] ; then
              yq -s -y '.[0].spec.triggers = [.[1].spec.triggers | add] | .[0]' $curdir/$SPEC $1 > $CF_BUILD_ID.yml
            else
              yq -s -y '.[0].spec.triggers = [.[].spec.triggers |.[]] | .[0]' $curdir/$SPEC $1 > $CF_BUILD_ID.yml
            fi
            mv $CF_BUILD_ID.yml $curdir/$SPEC
            count=$(expr $count + 1)
            return
          fi
          if [ -d $1 ] ; then
            process_dir $1
            return
          fi
          echo "Unknown file $1 - IGNORE"
          cf_export steps.create_pipeline.result="warning"
        }
        export curdir=`pwd`
        export count=1
        for f in `echo $TRIGGERS` ; do
            process_file $f
        done
        # cat $SPEC
        codefresh create pipeline -f $SPEC || codefresh replace -f $SPEC
