version: "1.0"

stages:
  - clone

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{ORG}}/${{REPO}}"
    revision: "master"
    stage: clone

  create_pipeline:
    title: "Creating pipeline"
    image: codefresh/cli
    working_directory: ${{REPO}}
    stage: clone
    commands:
      - |-
        echo "SPEC ${{SPEC}}"
        echo "TRIGGERS ${{TRIGGERS}}"
        process_dir() {
          echo  "process directory $f"
          set curdir=`pwd`
          cd $f
          for FILE in * ; do
            process_file $FILE
          done
          cd $curdir
        }
        process_file() {
          if [ -f $1 ]; then
            echo  "process file $1"
            yq merge $SPEC $1
            return
          fi
          if [ -d $1 ] ; then
            process_dir $f
            return
          fi
          echo "Unknown file $f - IGNORE"
        }
        for f in `echo $TRIGGERS` ; do
            process_file $f
        done
